# Generated by Django 6.0.6 on 2026-06-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
