# Generated by Django 6.0.6 on 2026-06-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cuota_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
